"""添加note(笔记)表

Revision ID: 13a8c3cf0b4a
Revises: 3991ab5b8153
Create Date: 2025-10-16 14:56:03.348539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a8c3cf0b4a'
down_revision = '3991ab5b8153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='笔记类型'),
    sa.Column('content', sa.Text(), nullable=True, comment='笔记内容'),
    sa.Column('tags', sa.String(length=255), nullable=True, comment='笔记标签'),
    sa.Column('folder', sa.String(length=255), nullable=True, comment='存储文件夹'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='是否已归档'),
    sa.Column('is_recycle', sa.Boolean(), nullable=False, comment='是否在回收站'),
    sa.Column('is_share', sa.Boolean(), nullable=False, comment='是否分享'),
    sa.Column('share_password', sa.String(length=255), nullable=True, comment='分享密码'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='账户ID'),
    sa.ForeignKeyConstraint(['account_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
