"""添加note_tags多对多关系表

Revision ID: 38fc47a66cd8
Revises: faac33ab224c
Create Date: 2025-11-05 21:35:15.293072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38fc47a66cd8'
down_revision = 'faac33ab224c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('tag_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_ids', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='笔记标签IDs'))

    # ### end Alembic commands ###
