"""Add tag table and modify note tag field

Revision ID: 3c6a7e212b51
Revises: 0f379059d151
Create Date: 2025-10-22 16:58:06.125872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c6a7e212b51'
down_revision = '0f379059d151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_ids', sa.String(length=255), nullable=True, comment='笔记标签IDs'))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='笔记标签'))
        batch_op.drop_column('tag_ids')

    # ### end Alembic commands ###
